# Site
name: "missyo"
title: "Missyo"
description: "学习·生活·反思"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl:
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  zhouzhaoxin:
    name: zhouzhaoxin 
    display_name: zhouzhaoxin 
    gravatar: 1fc7f3d27b80b4bb329ba3b3548f266c
    email: singleorb@gmail.com
    web: https://www.missyo.vip
    #twitter: https://twitter.com/wowthemesnet
    description: "主攻python，喜欢读书，喜欢摄影，芒格的忠实追随者。关注各个领域发展，取长补短，擅长结合多学科技术解决问题"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
    # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
